FROM ubuntu:plucky
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "cache buster 059a9a06-1686-4f49-9a7f-a30535886d55"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo podman netavark rsync vim dput devscripts dh-make dput git uidmap dbus-user-session tree python3 python3-venv cmake ninja-build libssl-dev
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN apt-get update
RUN apt-get -y install golang-1.24 eg egbootstrap libbtrfs-dev libassuan-dev libc6-dev libdevmapper-dev libglib2.0-dev libgpgme-dev libgpg-error-dev libprotobuf-dev libprotobuf-c-dev libseccomp-dev libselinux1-dev libsystemd-dev

RUN ln -s /usr/lib/go-1.24/bin/go /usr/local/bin/go

RUN systemd-sysusers
RUN systemd-tmpfiles --create
RUN usermod --add-subuids 100000-165535 --add-subgids 100000-165535 egd
RUN echo "cache buster 259a9a06-1996-4f49-9a3f-b30535886fd8"

RUN systemctl enable podman.socket
RUN podman version

