FROM ubuntu:plucky
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "cache buster 61571c95-0539-4f6e-bad4-f913db80e224"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo podman netavark rsync vim dput devscripts dh-make dput git uidmap dbus-user-session tree python3 python3-venv cmake ninja-build libssl-dev
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN echo "cache buster 61571c95-0539-4f6e-bad4-f913db80e225"
RUN apt-get update
RUN apt-get -y install golang-1.25 libbtrfs-dev libassuan-dev libc6-dev libdevmapper-dev libglib2.0-dev libgpgme-dev libgpg-error-dev libprotobuf-dev libprotobuf-c-dev libseccomp-dev libselinux1-dev libsystemd-dev

RUN ln -s /usr/lib/go-1.25/bin/go /usr/local/bin/go

RUN echo "cache buster 61571c95-0539-4f6e-bad4-f913db80e225"
RUN apt-get update
RUN apt-get -y install eg egbootstrap

RUN systemd-sysusers
RUN systemd-tmpfiles --create
RUN usermod --add-subuids 100000-165535 --add-subgids 100000-165535 egd
RUN echo "cache buster 3f48af53-7ae7-41da-960f-808788f6f886"

RUN systemctl enable podman.socket
RUN podman version

