FROM docker.io/library/archlinux:latest

COPY rootfs /

RUN systemd-sysusers
RUN systemd-tmpfiles --create
RUN pacman --noconfirm -Syu podman netavark pacman-contrib pkgfile foot sudo bash-completion tree base base-devel git go openssh rsync github-cli

CMD /usr/sbin/init
