// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: eg.actl.registration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels    []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Publickey []byte   `protobuf:"bytes,3,opt,name=publickey,json=pkey,proto3" json:"publickey,omitempty"`
	AuthzedAt string   `protobuf:"bytes,4,opt,name=authzed_at,json= authzed_at,proto3" json:"authzed_at,omitempty"`
	ExpiresAt string   `protobuf:"bytes,5,opt,name=expires_at,json= expires_at,proto3" json:"expires_at,omitempty"`
}

func (x *Registration) Reset() {
	*x = Registration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{0}
}

func (x *Registration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registration) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Registration) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Registration) GetAuthzedAt() string {
	if x != nil {
		return x.AuthzedAt
	}
	return ""
}

func (x *Registration) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type RegistrationSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegistrationSearchRequest) Reset() {
	*x = RegistrationSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSearchRequest) ProtoMessage() {}

func (x *RegistrationSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSearchRequest.ProtoReflect.Descriptor instead.
func (*RegistrationSearchRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{1}
}

type RegistrationSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Registration `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RegistrationSearchResponse) Reset() {
	*x = RegistrationSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSearchResponse) ProtoMessage() {}

func (x *RegistrationSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSearchResponse.ProtoReflect.Descriptor instead.
func (*RegistrationSearchResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationSearchResponse) GetItems() []*Registration {
	if x != nil {
		return x.Items
	}
	return nil
}

type RegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegistrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationResponse) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegistrationGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
}

func (x *RegistrationGrantRequest) Reset() {
	*x = RegistrationGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGrantRequest) ProtoMessage() {}

func (x *RegistrationGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGrantRequest.ProtoReflect.Descriptor instead.
func (*RegistrationGrantRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationGrantRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegistrationGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
}

func (x *RegistrationGrantResponse) Reset() {
	*x = RegistrationGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_registration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGrantResponse) ProtoMessage() {}

func (x *RegistrationGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGrantResponse.ProtoReflect.Descriptor instead.
func (*RegistrationGrantResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationGrantResponse) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

var File_eg_actl_registration_proto protoreflect.FileDescriptor

var file_eg_actl_registration_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x67,
	0x2e, 0x61, 0x63, 0x74, 0x6c, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x17,
	0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x70, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x7a,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x20, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x20, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x50, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63,
	0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a,
	0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eg_actl_registration_proto_rawDescOnce sync.Once
	file_eg_actl_registration_proto_rawDescData = file_eg_actl_registration_proto_rawDesc
)

func file_eg_actl_registration_proto_rawDescGZIP() []byte {
	file_eg_actl_registration_proto_rawDescOnce.Do(func() {
		file_eg_actl_registration_proto_rawDescData = protoimpl.X.CompressGZIP(file_eg_actl_registration_proto_rawDescData)
	})
	return file_eg_actl_registration_proto_rawDescData
}

var file_eg_actl_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_eg_actl_registration_proto_goTypes = []interface{}{
	(*Registration)(nil),               // 0: eg.actl.Registration
	(*RegistrationSearchRequest)(nil),  // 1: eg.actl.RegistrationSearchRequest
	(*RegistrationSearchResponse)(nil), // 2: eg.actl.RegistrationSearchResponse
	(*RegistrationRequest)(nil),        // 3: eg.actl.RegistrationRequest
	(*RegistrationResponse)(nil),       // 4: eg.actl.RegistrationResponse
	(*RegistrationGrantRequest)(nil),   // 5: eg.actl.RegistrationGrantRequest
	(*RegistrationGrantResponse)(nil),  // 6: eg.actl.RegistrationGrantResponse
}
var file_eg_actl_registration_proto_depIdxs = []int32{
	0, // 0: eg.actl.RegistrationSearchResponse.items:type_name -> eg.actl.Registration
	0, // 1: eg.actl.RegistrationRequest.registration:type_name -> eg.actl.Registration
	0, // 2: eg.actl.RegistrationResponse.registration:type_name -> eg.actl.Registration
	0, // 3: eg.actl.RegistrationGrantRequest.registration:type_name -> eg.actl.Registration
	0, // 4: eg.actl.RegistrationGrantResponse.registration:type_name -> eg.actl.Registration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_eg_actl_registration_proto_init() }
func file_eg_actl_registration_proto_init() {
	if File_eg_actl_registration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eg_actl_registration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_registration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eg_actl_registration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_actl_registration_proto_goTypes,
		DependencyIndexes: file_eg_actl_registration_proto_depIdxs,
		MessageInfos:      file_eg_actl_registration_proto_msgTypes,
	}.Build()
	File_eg_actl_registration_proto = out.File
	file_eg_actl_registration_proto_rawDesc = nil
	file_eg_actl_registration_proto_goTypes = nil
	file_eg_actl_registration_proto_depIdxs = nil
}
