//go:build !genieql.ignore
// +build !genieql.ignore

package egworkloads

import (
	"context"
	"database/sql"
	"math"
	"time"

	"github.com/egdaemon/eg/internal/ducktype"
	"github.com/egdaemon/eg/internal/sqlx"
	"github.com/gofrs/uuid/v5"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto graph -o genieql.gen.go
// invoked by go generate @ egworkloads/00.duckdb.setup.go line 3
//
// NOTE: hand-authored in place of a real genieql run -- the genieql binary
// wasn't available when this package was authored. Regenerate via
// `go generate ./...` (with genieql installed) once available, and this
// comment block should disappear along with the rest of this note.

// Discovered generated by genieql
type Discovered struct {
	ID   string
	Path string
	Ts   time.Time
}

// DiscoveredScanner scanner interface.
type DiscoveredScanner interface {
	Scan(i *Discovered) error
	Next() bool
	Close() error
	Err() error
}

type errDiscoveredScanner struct {
	e error
}

func (t errDiscoveredScanner) Scan(i *Discovered) error {
	return t.e
}

func (t errDiscoveredScanner) Next() bool {
	return false
}

func (t errDiscoveredScanner) Err() error {
	return t.e
}

func (t errDiscoveredScanner) Close() error {
	return nil
}

// DiscoveredScannerStaticColumns generated by genieql
const DiscoveredScannerStaticColumns = `eg_workloads_discovered."id",eg_workloads_discovered."path",eg_workloads_discovered."ts"`

// NewDiscoveredScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewDiscoveredScannerStatic(rows *sql.Rows, err error) DiscoveredScanner {
	if err != nil {
		return errDiscoveredScanner{e: err}
	}

	return discoveredScannerStatic{
		Rows: rows,
	}
}

// discoveredScannerStatic generated by genieql
type discoveredScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t discoveredScannerStatic) Scan(i *Discovered) error {
	var (
		c0 sql.NullString
		c1 sql.NullString
		c2 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2); err != nil {
		return err
	}

	if c0.Valid {
		if uid, err := uuid.FromBytes([]byte(c0.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	if c1.Valid {
		i.Path = c1.String
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		i.Ts = time.Unix(math.MaxInt64-62135596800, 999999999)
	case ducktype.NegativeInfinity:
		i.Ts = time.Unix(math.MinInt64, math.MinInt64)
	default:
		i.Ts = c2.Time
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t discoveredScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t discoveredScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t discoveredScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewDiscoveredScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewDiscoveredScannerStaticRow(row *sql.Row) DiscoveredScannerStaticRow {
	return DiscoveredScannerStaticRow{
		row: row,
	}
}

// DiscoveredScannerStaticRow generated by genieql
type DiscoveredScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t DiscoveredScannerStaticRow) Scan(i *Discovered) error {
	var (
		c0 sql.NullString
		c1 sql.NullString
		c2 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2); err != nil {
		return err
	}

	if c0.Valid {
		if uid, err := uuid.FromBytes([]byte(c0.String)); err != nil {
			return err
		} else {
			i.ID = uid.String()
		}
	}

	if c1.Valid {
		i.Path = c1.String
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		i.Ts = time.Unix(math.MaxInt64-62135596800, 999999999)
	case ducktype.NegativeInfinity:
		i.Ts = time.Unix(math.MinInt64, math.MinInt64)
	default:
		i.Ts = c2.Time
	}

	return nil
}

// DiscoveredInsert generated by genieql
func DiscoveredInsert(ctx context.Context, q sqlx.Queryer, w Discovered) DiscoveredScannerStaticRow {
	const query = `INSERT INTO eg_workloads_discovered ("id","path","ts") VALUES ($1,$2,$3) RETURNING "id","path","ts"`
	var (
		c0 sql.NullString    // id
		c1 sql.NullString    // path
		c2 ducktype.NullTime // ts
	)
	c0.Valid = true
	c0.String = w.ID
	c1.Valid = true
	c1.String = w.Path
	c2 = ducktype.NewNullTime(w.Ts)
	return NewDiscoveredScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2))
}

// DiscoveredLookup generated by genieql
func DiscoveredLookup(ctx context.Context, q sqlx.Queryer) DiscoveredScanner {
	const query = `SELECT ` + DiscoveredScannerStaticColumns + ` FROM eg_workloads_discovered ORDER BY ts DESC`
	return NewDiscoveredScannerStatic(q.QueryContext(ctx, query))
}
