//go:build !genieql.ignore
// +build !genieql.ignore

package egworkloads

import (
	"context"
	"database/sql"
	"math"
	"time"

	"github.com/egdaemon/eg/internal/ducktype"
	"github.com/egdaemon/eg/internal/sqlx"
	"github.com/gofrs/uuid/v5"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto graph -o genieql.gen.go
// invoked by go generate @ egworkloads/00.duckdb.setup.go line 5

// Discovered generated by genieql
type Discovered struct {
	ID   string
	Path string
	Ts   time.Time
}

// DiscoveredScanner scanner interface.
type DiscoveredScanner interface {
	Scan(w *Discovered) error
	Next() bool
	Close() error
	Err() error
}

type errDiscoveredScanner struct {
	e error
}

func (t errDiscoveredScanner) Scan(w *Discovered) error {
	return t.e
}

func (t errDiscoveredScanner) Next() bool {
	return false
}

func (t errDiscoveredScanner) Err() error {
	return t.e
}

func (t errDiscoveredScanner) Close() error {
	return nil
}

// DiscoveredScannerStaticColumns generated by genieql
const DiscoveredScannerStaticColumns = `"id","path","ts"`

// NewDiscoveredScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewDiscoveredScannerStatic(rows *sql.Rows, err error) DiscoveredScanner {
	if err != nil {
		return errDiscoveredScanner{e: err}
	}

	return discoveredScannerStatic{
		Rows: rows,
	}
}

// discoveredScannerStatic generated by genieql
type discoveredScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t discoveredScannerStatic) Scan(w *Discovered) error {
	var (
		c0 sql.NullString
		c1 sql.NullString
		c2 ducktype.NullTime
	)

	if err := t.Rows.Scan(&c0, &c1, &c2); err != nil {
		return err
	}

	if c0.Valid {
		if uid, err := uuid.FromBytes([]byte(c0.String)); err != nil {
			return err
		} else {
			tmp := uid.String()
			w.ID = tmp
		}
	}

	if c1.Valid {
		tmp := string(c1.String)
		w.Path = tmp
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		w.Ts = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		w.Ts = tmp
	default:
		tmp := c2.Time
		w.Ts = tmp
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t discoveredScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t discoveredScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t discoveredScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewDiscoveredScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewDiscoveredScannerStaticRow(row *sql.Row) DiscoveredScannerStaticRow {
	return DiscoveredScannerStaticRow{
		row: row,
	}
}

// DiscoveredScannerStaticRow generated by genieql
type DiscoveredScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t DiscoveredScannerStaticRow) Scan(w *Discovered) error {
	var (
		c0 sql.NullString
		c1 sql.NullString
		c2 ducktype.NullTime
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2); err != nil {
		return err
	}

	if c0.Valid {
		if uid, err := uuid.FromBytes([]byte(c0.String)); err != nil {
			return err
		} else {
			tmp := uid.String()
			w.ID = tmp
		}
	}

	if c1.Valid {
		tmp := string(c1.String)
		w.Path = tmp
	}

	switch c2.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		w.Ts = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		w.Ts = tmp
	default:
		tmp := c2.Time
		w.Ts = tmp
	}

	return nil
}

// Err set an error to return by scan
func (t DiscoveredScannerStaticRow) Err(err error) DiscoveredScannerStaticRow {
	t.err = err
	return t
}

// NewDiscoveredScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewDiscoveredScannerDynamic(rows *sql.Rows, err error) DiscoveredScanner {
	if err != nil {
		return errDiscoveredScanner{e: err}
	}

	return discoveredScannerDynamic{
		Rows: rows,
	}
}

// discoveredScannerDynamic generated by genieql
type discoveredScannerDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t discoveredScannerDynamic) Scan(w *Discovered) error {
	const (
		cn0 = "id"
		cn1 = "path"
		cn2 = "ts"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      sql.NullString
		c1      sql.NullString
		c2      ducktype.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if c0.Valid {
				if uid, err := uuid.FromBytes([]byte(c0.String)); err != nil {
					return err
				} else {
					tmp := uid.String()
					w.ID = tmp
				}
			}

		case cn1:
			if c1.Valid {
				tmp := string(c1.String)
				w.Path = tmp
			}

		case cn2:
			switch c2.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				w.Ts = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				w.Ts = tmp
			default:
				tmp := c2.Time
				w.Ts = tmp
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t discoveredScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t discoveredScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t discoveredScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// DiscoveredInsertStaticColumns generated by genieql
const DiscoveredInsertStaticColumns = `$1,$2,$3`

// DiscoveredInsertExplode generated by genieql
func DiscoveredInsertExplode(w *Discovered) ([]interface{}, error) {
	var (
		c0 sql.NullString    // id
		c1 sql.NullString    // path
		c2 ducktype.NullTime // ts
	)

	c0.Valid = true
	c0.String = w.ID

	c1.Valid = true
	c1.String = w.Path

	switch ts := w.Ts; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c2.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c2.NegativeInfinity()
	default:
		c2.Status = ducktype.Present
		c2.Time = w.Ts
	}

	return []interface{}{c0, c1, c2}, nil
}

// DiscoveredInsert generated by genieql
func DiscoveredInsert(ctx context.Context, q sqlx.Queryer, w Discovered) DiscoveredScannerStaticRow {
	const query = `INSERT INTO "eg_workloads_discovered" ("id","path","ts") VALUES ($1,$2,$3) RETURNING "id","path","ts"`
	var (
		c0 sql.NullString // id
		c1 sql.NullString // path
		c2 ducktype.NullTime
	)
	c0.Valid = true
	c0.String = w.ID
	c1.Valid = true
	c1.String = w.Path
	switch ts := w.Ts; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c2.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c2.NegativeInfinity()
	default:
		c2.Status = ducktype.Present
		c2.Time = w.Ts
	} // ts
	return NewDiscoveredScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2))
}

// DiscoveredLookup generated by genieql
func DiscoveredLookup(ctx context.Context, q sqlx.Queryer) DiscoveredScanner {
	const query = `SELECT "id","path","ts" FROM eg_workloads_discovered ORDER BY ts DESC`
	return NewDiscoveredScannerStatic(q.QueryContext(ctx, query))
}
