FROM ubuntu:noble

ARG DEBIAN_FRONTEND=noninteractive
ARG EG_RUNNER_OVERRIDE_DIR=/usr/share/eg/rootfs

COPY ${EG_RUNNER_OVERRIDE_DIR} /

RUN apt-get update
RUN apt-get -y install software-properties-common build-essential apt-file podman rsync vim dput devscripts dh-make dput git uidmap dbus-user-session fuse-overlayfs pinentry-tty fuse3
# RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:jljatone/eg
RUN apt-get update
RUN apt-get -y install eg
RUN usermod --add-subuids 200000-265536 --add-subgids 200000-265536 root
RUN systemctl enable eg-daemon.service

CMD /usr/sbin/init
