FROM ubuntu:resolute

# used to cause rebuilds automatically when the version changes.
ARG EG_VERSION="${EG_VERSION}"
ARG DEBIAN_FRONTEND=noninteractive
ARG EG_RUNNER_OVERRIDE_DIR=/usr/share/eg/rootfs

COPY ${EG_RUNNER_OVERRIDE_DIR} /

RUN apt-get update
RUN apt-get -y install software-properties-common build-essential apt-file netavark rsync vim dput devscripts dh-make dput git uidmap dbus-user-session fuse-overlayfs inetutils-ping iproute2
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb
RUN apt-get update
RUN apt-get -y install egworkload

RUN systemctl enable eg-daemon.service eg-daily-reload.service eg-disk-usage.service

# preload some wellknown hosts
RUN ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts
RUN ssh-keyscan -H gitlab.com >> /etc/ssh/ssh_known_hosts

CMD /usr/sbin/init
