// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: eg.actl.registration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Publickey     []byte                 `protobuf:"bytes,3,opt,name=publickey,json=pkey,proto3" json:"publickey,omitempty"`
	AuthzedAt     string                 `protobuf:"bytes,4,opt,name=authzed_at,proto3" json:"authzed_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	P2Pid         string                 `protobuf:"bytes,6,opt,name=p2pid,proto3" json:"p2pid,omitempty"`
	Os            string                 `protobuf:"bytes,900,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,901,opt,name=arch,proto3" json:"arch,omitempty"` // the native architecture.
	Cores         uint64                 `protobuf:"varint,902,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory        uint64                 `protobuf:"varint,903,opt,name=memory,proto3" json:"memory,omitempty"`
	Labels        []string               `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_eg_actl_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{0}
}

func (x *Registration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Registration) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Registration) GetAuthzedAt() string {
	if x != nil {
		return x.AuthzedAt
	}
	return ""
}

func (x *Registration) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Registration) GetP2Pid() string {
	if x != nil {
		return x.P2Pid
	}
	return ""
}

func (x *Registration) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Registration) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Registration) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Registration) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Registration) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_eg_actl_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bootstrap     []string               `protobuf:"bytes,1000,rep,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_eg_actl_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetBootstrap() []string {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_eg_actl_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Bootstrap     []string               `protobuf:"bytes,1000,rep,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_eg_actl_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationResponse) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *RegistrationResponse) GetBootstrap() []string {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type RegistrationGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Global        bool                   `protobuf:"varint,2,opt,name=global,proto3" json:"global,omitempty"`
	Expiration    uint64                 `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationGrantRequest) Reset() {
	*x = RegistrationGrantRequest{}
	mi := &file_eg_actl_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGrantRequest) ProtoMessage() {}

func (x *RegistrationGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGrantRequest.ProtoReflect.Descriptor instead.
func (*RegistrationGrantRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationGrantRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *RegistrationGrantRequest) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *RegistrationGrantRequest) GetExpiration() uint64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type RegistrationGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationGrantResponse) Reset() {
	*x = RegistrationGrantResponse{}
	mi := &file_eg_actl_registration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationGrantResponse) ProtoMessage() {}

func (x *RegistrationGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationGrantResponse.ProtoReflect.Descriptor instead.
func (*RegistrationGrantResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationGrantResponse) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type RegistrationSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationSearchRequest) Reset() {
	*x = RegistrationSearchRequest{}
	mi := &file_eg_actl_registration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSearchRequest) ProtoMessage() {}

func (x *RegistrationSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSearchRequest.ProtoReflect.Descriptor instead.
func (*RegistrationSearchRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{7}
}

type RegistrationSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Registration        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationSearchResponse) Reset() {
	*x = RegistrationSearchResponse{}
	mi := &file_eg_actl_registration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSearchResponse) ProtoMessage() {}

func (x *RegistrationSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_registration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSearchResponse.ProtoReflect.Descriptor instead.
func (*RegistrationSearchResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_registration_proto_rawDescGZIP(), []int{8}
}

func (x *RegistrationSearchResponse) GetItems() []*Registration {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_eg_actl_registration_proto protoreflect.FileDescriptor

var file_eg_actl_registration_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x67,
	0x2e, 0x61, 0x63, 0x74, 0x6c, 0x22, 0xa5, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x6b, 0x65,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x32, 0x70, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x32, 0x70, 0x69, 0x64, 0x12, 0x0f, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x84, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x13, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68,
	0x18, 0x85, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x15, 0x0a,
	0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x86, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x87,
	0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a,
	0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4a, 0x05, 0x08, 0x07, 0x10, 0x84, 0x07, 0x22, 0x48, 0x0a,
	0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x22, 0x50, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x22, 0x8d, 0x01, 0x0a, 0x18, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x19, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x49, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65,
	0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_eg_actl_registration_proto_rawDescOnce sync.Once
	file_eg_actl_registration_proto_rawDescData []byte
)

func file_eg_actl_registration_proto_rawDescGZIP() []byte {
	file_eg_actl_registration_proto_rawDescOnce.Do(func() {
		file_eg_actl_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eg_actl_registration_proto_rawDesc), len(file_eg_actl_registration_proto_rawDesc)))
	})
	return file_eg_actl_registration_proto_rawDescData
}

var file_eg_actl_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_eg_actl_registration_proto_goTypes = []any{
	(*Registration)(nil),               // 0: eg.actl.Registration
	(*PingRequest)(nil),                // 1: eg.actl.PingRequest
	(*PingResponse)(nil),               // 2: eg.actl.PingResponse
	(*RegistrationRequest)(nil),        // 3: eg.actl.RegistrationRequest
	(*RegistrationResponse)(nil),       // 4: eg.actl.RegistrationResponse
	(*RegistrationGrantRequest)(nil),   // 5: eg.actl.RegistrationGrantRequest
	(*RegistrationGrantResponse)(nil),  // 6: eg.actl.RegistrationGrantResponse
	(*RegistrationSearchRequest)(nil),  // 7: eg.actl.RegistrationSearchRequest
	(*RegistrationSearchResponse)(nil), // 8: eg.actl.RegistrationSearchResponse
}
var file_eg_actl_registration_proto_depIdxs = []int32{
	0, // 0: eg.actl.PingRequest.registration:type_name -> eg.actl.Registration
	0, // 1: eg.actl.RegistrationRequest.registration:type_name -> eg.actl.Registration
	0, // 2: eg.actl.RegistrationResponse.registration:type_name -> eg.actl.Registration
	0, // 3: eg.actl.RegistrationGrantRequest.registration:type_name -> eg.actl.Registration
	0, // 4: eg.actl.RegistrationGrantResponse.registration:type_name -> eg.actl.Registration
	0, // 5: eg.actl.RegistrationSearchResponse.items:type_name -> eg.actl.Registration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_eg_actl_registration_proto_init() }
func file_eg_actl_registration_proto_init() {
	if File_eg_actl_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eg_actl_registration_proto_rawDesc), len(file_eg_actl_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_actl_registration_proto_goTypes,
		DependencyIndexes: file_eg_actl_registration_proto_depIdxs,
		MessageInfos:      file_eg_actl_registration_proto_msgTypes,
	}.Build()
	File_eg_actl_registration_proto = out.File
	file_eg_actl_registration_proto_goTypes = nil
	file_eg_actl_registration_proto_depIdxs = nil
}
