// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: eg.compute.proto

package compute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,14,opt,name=cluster_id,json=cid,proto3" json:"cluster_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	AuthzedAt     string                 `protobuf:"bytes,7,opt,name=authzed_at,proto3" json:"authzed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compute) Reset() {
	*x = Compute{}
	mi := &file_eg_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compute) ProtoMessage() {}

func (x *Compute) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compute.ProtoReflect.Descriptor instead.
func (*Compute) Descriptor() ([]byte, []int) {
	return file_eg_compute_proto_rawDescGZIP(), []int{0}
}

func (x *Compute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Compute) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Compute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Compute) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Compute) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Compute) GetAuthzedAt() string {
	if x != nil {
		return x.AuthzedAt
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Global        bool                   `protobuf:"varint,2,opt,name=global,proto3" json:"global,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Cores         uint64                 `protobuf:"varint,5,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory        uint64                 `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Vram          uint64                 `protobuf:"varint,7,opt,name=vram,proto3" json:"vram,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	Labels        []string               `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_eg_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_eg_compute_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *SearchRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SearchRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SearchRequest) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *SearchRequest) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SearchRequest) GetVram() uint64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *SearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *SearchRequest         `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Compute             `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_eg_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_eg_compute_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetNext() *SearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *SearchResponse) GetItems() []*Compute {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_eg_compute_proto protoreflect.FileDescriptor

const file_eg_compute_proto_rawDesc = "" +
	"\n" +
	"\x10eg.compute.proto\x12\n" +
	"eg.compute\"\xb4\x01\n" +
	"\aCompute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\n" +
	"cluster_id\x18\x0e \x01(\tR\x03cid\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\n" +
	"updated_at\x12\x1e\n" +
	"\n" +
	"authzed_at\x18\a \x01(\tR\n" +
	"authzed_at\"\xfb\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06global\x18\x02 \x01(\bR\x06global\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x14\n" +
	"\x05cores\x18\x05 \x01(\x04R\x05cores\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\x04R\x06memory\x12\x12\n" +
	"\x04vram\x18\a \x01(\x04R\x04vram\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limit\x12\x17\n" +
	"\x06labels\x18\xe8\a \x03(\tR\x06labelsJ\x05\b\b\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"j\n" +
	"\x0eSearchResponse\x12-\n" +
	"\x04next\x18\x01 \x01(\v2\x19.eg.compute.SearchRequestR\x04next\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.eg.compute.ComputeR\x05itemsb\x06proto3"

var (
	file_eg_compute_proto_rawDescOnce sync.Once
	file_eg_compute_proto_rawDescData []byte
)

func file_eg_compute_proto_rawDescGZIP() []byte {
	file_eg_compute_proto_rawDescOnce.Do(func() {
		file_eg_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eg_compute_proto_rawDesc), len(file_eg_compute_proto_rawDesc)))
	})
	return file_eg_compute_proto_rawDescData
}

var file_eg_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eg_compute_proto_goTypes = []any{
	(*Compute)(nil),        // 0: eg.compute.Compute
	(*SearchRequest)(nil),  // 1: eg.compute.SearchRequest
	(*SearchResponse)(nil), // 2: eg.compute.SearchResponse
}
var file_eg_compute_proto_depIdxs = []int32{
	1, // 0: eg.compute.SearchResponse.next:type_name -> eg.compute.SearchRequest
	0, // 1: eg.compute.SearchResponse.items:type_name -> eg.compute.Compute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eg_compute_proto_init() }
func file_eg_compute_proto_init() {
	if File_eg_compute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eg_compute_proto_rawDesc), len(file_eg_compute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_compute_proto_goTypes,
		DependencyIndexes: file_eg_compute_proto_depIdxs,
		MessageInfos:      file_eg_compute_proto_msgTypes,
	}.Build()
	File_eg_compute_proto = out.File
	file_eg_compute_proto_goTypes = nil
	file_eg_compute_proto_depIdxs = nil
}
