// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: eg.compute.vcs.proto

package compute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitCredentialsAutomatic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GitCredentialsAutomatic) Reset() {
	*x = GitCredentialsAutomatic{}
	mi := &file_eg_compute_vcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCredentialsAutomatic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCredentialsAutomatic) ProtoMessage() {}

func (x *GitCredentialsAutomatic) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_vcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCredentialsAutomatic.ProtoReflect.Descriptor instead.
func (*GitCredentialsAutomatic) Descriptor() ([]byte, []int) {
	return file_eg_compute_vcs_proto_rawDescGZIP(), []int{0}
}

type GitCredentialsHTTP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GitCredentialsHTTP) Reset() {
	*x = GitCredentialsHTTP{}
	mi := &file_eg_compute_vcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCredentialsHTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCredentialsHTTP) ProtoMessage() {}

func (x *GitCredentialsHTTP) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_vcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCredentialsHTTP.ProtoReflect.Descriptor instead.
func (*GitCredentialsHTTP) Descriptor() ([]byte, []int) {
	return file_eg_compute_vcs_proto_rawDescGZIP(), []int{1}
}

func (x *GitCredentialsHTTP) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GitCredentialsHTTP) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GitAccessCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Credentials:
	//
	//	*GitAccessCredentials_Automatic
	//	*GitAccessCredentials_GitHttp
	Credentials isGitAccessCredentials_Credentials `protobuf_oneof:"Credentials"`
}

func (x *GitAccessCredentials) Reset() {
	*x = GitAccessCredentials{}
	mi := &file_eg_compute_vcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitAccessCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitAccessCredentials) ProtoMessage() {}

func (x *GitAccessCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_eg_compute_vcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitAccessCredentials.ProtoReflect.Descriptor instead.
func (*GitAccessCredentials) Descriptor() ([]byte, []int) {
	return file_eg_compute_vcs_proto_rawDescGZIP(), []int{2}
}

func (m *GitAccessCredentials) GetCredentials() isGitAccessCredentials_Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (x *GitAccessCredentials) GetAutomatic() *GitCredentialsAutomatic {
	if x, ok := x.GetCredentials().(*GitAccessCredentials_Automatic); ok {
		return x.Automatic
	}
	return nil
}

func (x *GitAccessCredentials) GetGitHttp() *GitCredentialsHTTP {
	if x, ok := x.GetCredentials().(*GitAccessCredentials_GitHttp); ok {
		return x.GitHttp
	}
	return nil
}

type isGitAccessCredentials_Credentials interface {
	isGitAccessCredentials_Credentials()
}

type GitAccessCredentials_Automatic struct {
	Automatic *GitCredentialsAutomatic `protobuf:"bytes,100,opt,name=automatic,proto3,oneof"`
}

type GitAccessCredentials_GitHttp struct {
	GitHttp *GitCredentialsHTTP `protobuf:"bytes,101,opt,name=git_http,json=gitHttp,proto3,oneof"`
}

func (*GitAccessCredentials_Automatic) isGitAccessCredentials_Credentials() {}

func (*GitAccessCredentials_GitHttp) isGitAccessCredentials_Credentials() {}

var File_eg_compute_vcs_proto protoreflect.FileDescriptor

var file_eg_compute_vcs_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x63, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x69, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x22, 0x4c, 0x0a,
	0x12, 0x47, 0x69, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48,
	0x54, 0x54, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x14,
	0x47, 0x69, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69,
	0x63, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x67, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x2e, 0x47, 0x69, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x48, 0x00, 0x52, 0x09,
	0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x12, 0x3b, 0x0a, 0x08, 0x67, 0x69, 0x74,
	0x5f, 0x68, 0x74, 0x74, 0x70, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x67,
	0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x47, 0x69, 0x74, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48, 0x54, 0x54, 0x50, 0x48, 0x00, 0x52, 0x07, 0x67,
	0x69, 0x74, 0x48, 0x74, 0x74, 0x70, 0x42, 0x0d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eg_compute_vcs_proto_rawDescOnce sync.Once
	file_eg_compute_vcs_proto_rawDescData = file_eg_compute_vcs_proto_rawDesc
)

func file_eg_compute_vcs_proto_rawDescGZIP() []byte {
	file_eg_compute_vcs_proto_rawDescOnce.Do(func() {
		file_eg_compute_vcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_eg_compute_vcs_proto_rawDescData)
	})
	return file_eg_compute_vcs_proto_rawDescData
}

var file_eg_compute_vcs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eg_compute_vcs_proto_goTypes = []any{
	(*GitCredentialsAutomatic)(nil), // 0: eg.compute.GitCredentialsAutomatic
	(*GitCredentialsHTTP)(nil),      // 1: eg.compute.GitCredentialsHTTP
	(*GitAccessCredentials)(nil),    // 2: eg.compute.GitAccessCredentials
}
var file_eg_compute_vcs_proto_depIdxs = []int32{
	0, // 0: eg.compute.GitAccessCredentials.automatic:type_name -> eg.compute.GitCredentialsAutomatic
	1, // 1: eg.compute.GitAccessCredentials.git_http:type_name -> eg.compute.GitCredentialsHTTP
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eg_compute_vcs_proto_init() }
func file_eg_compute_vcs_proto_init() {
	if File_eg_compute_vcs_proto != nil {
		return
	}
	file_eg_compute_vcs_proto_msgTypes[2].OneofWrappers = []any{
		(*GitAccessCredentials_Automatic)(nil),
		(*GitAccessCredentials_GitHttp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eg_compute_vcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_compute_vcs_proto_goTypes,
		DependencyIndexes: file_eg_compute_vcs_proto_depIdxs,
		MessageInfos:      file_eg_compute_vcs_proto_msgTypes,
	}.Build()
	File_eg_compute_vcs_proto = out.File
	file_eg_compute_vcs_proto_rawDesc = nil
	file_eg_compute_vcs_proto_goTypes = nil
	file_eg_compute_vcs_proto_depIdxs = nil
}
