FROM ubuntu:jammy
# ARG DEBIAN_FRONTEND=noninteractive

COPY .dist/.build.filesystem /

RUN apt-get update
RUN apt-get -y install software-properties-common build-essential apt-file
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:jljatone/eg
RUN apt-get update
RUN apt-get -y install dput devscripts dh-make dput git uidmap dbus-user-session fuse-overlayfs
RUN apt-get -y install golang-1.22 podman rsync vim eg
RUN apt-get -y install pinentry-tty
RUN podman --version
RUN usermod --add-subuids 200000-265536 --add-subgids 200000-265536 root

CMD /usr/sbin/init
