FROM ubuntu:jammy
# ARG DEBIAN_FRONTEND=noninteractive

COPY .dist/.build.filesystem /

RUN apt-get update
RUN apt-get -y --no-install-recommends install dput devscripts dh-make dput software-properties-common git uidmap dbus-user-session fuse-overlayfs
RUN add-apt-repository ppa:longsleep/golang-backports
RUN apt-get update
RUN apt-get -y --no-install-recommends install golang-1.21 podman podman-remote rsync vim build-essential apt-file
RUN podman --version
RUN podman-remote --version
RUN usermod --add-subuids 100000-200000 --add-subgids 100000-200000 root

CMD /usr/sbin/init
