// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: eg.duckproxy.proto

package duckproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Param mirrors database/sql/driver.NamedValue.
type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordinal       int32                  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_eg_duckproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{0}
}

func (x *Param) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Value describes a single DuckDB-native value crossing the wire. Unlike a
// Postgres OID table, this only needs to describe DuckDB's own types --
// both ends of this protocol are DuckDB.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_IsNull
	//	*Value_BoolValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	//	*Value_IntervalValue
	//	*Value_DecimalValue
	//	*Value_BignumValue
	//	*Value_ListValue
	//	*Value_StructValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_eg_duckproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *Value) GetIntervalValue() *Interval {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntervalValue); ok {
			return x.IntervalValue
		}
	}
	return nil
}

func (x *Value) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

func (x *Value) GetBignumValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_BignumValue); ok {
			return x.BignumValue
		}
	}
	return ""
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_IsNull struct {
	IsNull bool `protobuf:"varint,1,opt,name=is_null,json=isNull,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_IntervalValue struct {
	IntervalValue *Interval `protobuf:"bytes,8,opt,name=interval_value,json=intervalValue,proto3,oneof"`
}

type Value_DecimalValue struct {
	DecimalValue string `protobuf:"bytes,9,opt,name=decimal_value,json=decimalValue,proto3,oneof"` // duckdb.Decimal.String()
}

type Value_BignumValue struct {
	BignumValue string `protobuf:"bytes,10,opt,name=bignum_value,json=bignumValue,proto3,oneof"` // *big.Int (HUGEINT/UHUGEINT) base-10 string
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,11,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,12,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Value_IsNull) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_IntervalValue) isValue_Kind() {}

func (*Value_DecimalValue) isValue_Kind() {}

func (*Value_BignumValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Months        int32                  `protobuf:"varint,1,opt,name=months,proto3" json:"months,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Micros        int64                  `protobuf:"varint,3,opt,name=micros,proto3" json:"micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_eg_duckproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Interval) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *Interval) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *Interval) GetMicros() int64 {
	if x != nil {
		return x.Micros
	}
	return 0
}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_eg_duckproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{3}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_eg_duckproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{4}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Args          []*Param               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecRequest) GetArgs() []*Param {
	if x != nil {
		return x.Args
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Args          []*Param               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetArgs() []*Param {
	if x != nil {
		return x.Args
	}
	return nil
}

type BeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{7}
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{8}
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{9}
}

// DescribeRequest prepares sql without executing it, purely to learn
// parameter/result type info ahead of time -- needed by Postgres-wire
// frontends (duckpgwire) for ParameterDescription/RowDescription, which
// neither end of this protocol otherwise needs.
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_eg_duckproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

// TypeMetadata pairs a DuckDB type with whatever identifies its slot, so
// callers don't have to index two parallel arrays together. Name is empty
// for parameters, which are positional ($1, $2, ...), not named.
type TypeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // duckdb.Type enum value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMetadata) Reset() {
	*x = TypeMetadata{}
	mi := &file_eg_duckproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMetadata) ProtoMessage() {}

func (x *TypeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMetadata.ProtoReflect.Descriptor instead.
func (*TypeMetadata) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{11}
}

func (x *TypeMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeMetadata) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        bool                   `protobuf:"varint,1,opt,name=tuples,proto3" json:"tuples,omitempty"` // whether this statement returns rows
	Params        []*TypeMetadata        `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Columns       []*TypeMetadata        `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	StatementType uint32                 `protobuf:"varint,4,opt,name=statement_type,json=statementType,proto3" json:"statement_type,omitempty"` // duckdb.StmtType enum value (distinct enum from TypeMetadata.type)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeResponse) GetTuples() bool {
	if x != nil {
		return x.Tuples
	}
	return false
}

func (x *DescribeResponse) GetParams() []*TypeMetadata {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DescribeResponse) GetColumns() []*TypeMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DescribeResponse) GetStatementType() uint32 {
	if x != nil {
		return x.StatementType
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int64                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ExecResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type ColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnsResponse) Reset() {
	*x = ColumnsResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnsResponse) ProtoMessage() {}

func (x *ColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnsResponse.ProtoReflect.Descriptor instead.
func (*ColumnsResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{14}
}

func (x *ColumnsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type RowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowResponse) Reset() {
	*x = RowResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowResponse) ProtoMessage() {}

func (x *RowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowResponse.ProtoReflect.Descriptor instead.
func (*RowResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{15}
}

func (x *RowResponse) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type DoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneResponse) Reset() {
	*x = DoneResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneResponse) ProtoMessage() {}

func (x *DoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneResponse.ProtoReflect.Descriptor instead.
func (*DoneResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{16}
}

type OkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{17}
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_eg_duckproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ClientFrame is one request, sent client -> server.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Exec
	//	*ClientFrame_Query
	//	*ClientFrame_Begin
	//	*ClientFrame_Commit
	//	*ClientFrame_Rollback
	//	*ClientFrame_Describe
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_eg_duckproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{19}
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ClientFrame) GetQuery() *QueryRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *ClientFrame) GetBegin() *BeginRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *ClientFrame) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *ClientFrame) GetRollback() *RollbackRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *ClientFrame) GetDescribe() *DescribeRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Describe); ok {
			return x.Describe
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type ClientFrame_Query struct {
	Query *QueryRequest `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

type ClientFrame_Begin struct {
	Begin *BeginRequest `protobuf:"bytes,3,opt,name=begin,proto3,oneof"`
}

type ClientFrame_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type ClientFrame_Rollback struct {
	Rollback *RollbackRequest `protobuf:"bytes,5,opt,name=rollback,proto3,oneof"`
}

type ClientFrame_Describe struct {
	Describe *DescribeRequest `protobuf:"bytes,6,opt,name=describe,proto3,oneof"`
}

func (*ClientFrame_Exec) isClientFrame_Body() {}

func (*ClientFrame_Query) isClientFrame_Body() {}

func (*ClientFrame_Begin) isClientFrame_Body() {}

func (*ClientFrame_Commit) isClientFrame_Body() {}

func (*ClientFrame_Rollback) isClientFrame_Body() {}

func (*ClientFrame_Describe) isClientFrame_Body() {}

// ServerFrame is one response, sent server -> client. Query responses are
// one ColumnsResponse followed by zero or more RowResponse frames and a
// terminal DoneResponse; an ErrorResponse may replace any terminal frame,
// including after RowResponse frames have already been streamed.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Result
	//	*ServerFrame_Columns
	//	*ServerFrame_Row
	//	*ServerFrame_Done
	//	*ServerFrame_Ok
	//	*ServerFrame_Error
	//	*ServerFrame_Describe
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_eg_duckproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_eg_duckproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_eg_duckproxy_proto_rawDescGZIP(), []int{20}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetResult() *ExecResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerFrame) GetColumns() *ColumnsResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Columns); ok {
			return x.Columns
		}
	}
	return nil
}

func (x *ServerFrame) GetRow() *RowResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Row); ok {
			return x.Row
		}
	}
	return nil
}

func (x *ServerFrame) GetDone() *DoneResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ServerFrame) GetOk() *OkResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetDescribe() *DescribeResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Describe); ok {
			return x.Describe
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Result struct {
	Result *ExecResponse `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type ServerFrame_Columns struct {
	Columns *ColumnsResponse `protobuf:"bytes,2,opt,name=columns,proto3,oneof"`
}

type ServerFrame_Row struct {
	Row *RowResponse `protobuf:"bytes,3,opt,name=row,proto3,oneof"`
}

type ServerFrame_Done struct {
	Done *DoneResponse `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

type ServerFrame_Ok struct {
	Ok *OkResponse `protobuf:"bytes,5,opt,name=ok,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ServerFrame_Describe struct {
	Describe *DescribeResponse `protobuf:"bytes,7,opt,name=describe,proto3,oneof"`
}

func (*ServerFrame_Result) isServerFrame_Body() {}

func (*ServerFrame_Columns) isServerFrame_Body() {}

func (*ServerFrame_Row) isServerFrame_Body() {}

func (*ServerFrame_Done) isServerFrame_Body() {}

func (*ServerFrame_Ok) isServerFrame_Body() {}

func (*ServerFrame_Error) isServerFrame_Body() {}

func (*ServerFrame_Describe) isServerFrame_Body() {}

var File_eg_duckproxy_proto protoreflect.FileDescriptor

const file_eg_duckproxy_proto_rawDesc = "" +
	"\n" +
	"\x12eg.duckproxy.proto\x12\feg.duckproxy\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n" +
	"\x05Param\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x05value\x18\x03 \x01(\v2\x13.eg.duckproxy.ValueR\x05value\"\xa5\x04\n" +
	"\x05Value\x12\x19\n" +
	"\ais_null\x18\x01 \x01(\bH\x00R\x06isNull\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x06 \x01(\fH\x00R\n" +
	"bytesValue\x12E\n" +
	"\x0ftimestamp_value\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12?\n" +
	"\x0einterval_value\x18\b \x01(\v2\x16.eg.duckproxy.IntervalH\x00R\rintervalValue\x12%\n" +
	"\rdecimal_value\x18\t \x01(\tH\x00R\fdecimalValue\x12#\n" +
	"\fbignum_value\x18\n" +
	" \x01(\tH\x00R\vbignumValue\x128\n" +
	"\n" +
	"list_value\x18\v \x01(\v2\x17.eg.duckproxy.ListValueH\x00R\tlistValue\x12>\n" +
	"\fstruct_value\x18\f \x01(\v2\x19.eg.duckproxy.StructValueH\x00R\vstructValueB\x06\n" +
	"\x04kind\"N\n" +
	"\bInterval\x12\x16\n" +
	"\x06months\x18\x01 \x01(\x05R\x06months\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\x16\n" +
	"\x06micros\x18\x03 \x01(\x03R\x06micros\"8\n" +
	"\tListValue\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.eg.duckproxy.ValueR\x06values\"\x9c\x01\n" +
	"\vStructValue\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.eg.duckproxy.StructValue.FieldsEntryR\x06fields\x1aN\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.eg.duckproxy.ValueR\x05value:\x028\x01\"H\n" +
	"\vExecRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12'\n" +
	"\x04args\x18\x02 \x03(\v2\x13.eg.duckproxy.ParamR\x04args\"I\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12'\n" +
	"\x04args\x18\x02 \x03(\v2\x13.eg.duckproxy.ParamR\x04args\"\x0e\n" +
	"\fBeginRequest\"\x0f\n" +
	"\rCommitRequest\"\x11\n" +
	"\x0fRollbackRequest\"#\n" +
	"\x0fDescribeRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"6\n" +
	"\fTypeMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\"\xbb\x01\n" +
	"\x10DescribeResponse\x12\x16\n" +
	"\x06tuples\x18\x01 \x01(\bR\x06tuples\x122\n" +
	"\x06params\x18\x02 \x03(\v2\x1a.eg.duckproxy.TypeMetadataR\x06params\x124\n" +
	"\acolumns\x18\x03 \x03(\v2\x1a.eg.duckproxy.TypeMetadataR\acolumns\x12%\n" +
	"\x0estatement_type\x18\x04 \x01(\rR\rstatementType\"3\n" +
	"\fExecResponse\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected\"'\n" +
	"\x0fColumnsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\":\n" +
	"\vRowResponse\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.eg.duckproxy.ValueR\x06values\"\x0e\n" +
	"\fDoneResponse\"\f\n" +
	"\n" +
	"OkResponse\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xdf\x02\n" +
	"\vClientFrame\x12/\n" +
	"\x04exec\x18\x01 \x01(\v2\x19.eg.duckproxy.ExecRequestH\x00R\x04exec\x122\n" +
	"\x05query\x18\x02 \x01(\v2\x1a.eg.duckproxy.QueryRequestH\x00R\x05query\x122\n" +
	"\x05begin\x18\x03 \x01(\v2\x1a.eg.duckproxy.BeginRequestH\x00R\x05begin\x125\n" +
	"\x06commit\x18\x04 \x01(\v2\x1b.eg.duckproxy.CommitRequestH\x00R\x06commit\x12;\n" +
	"\brollback\x18\x05 \x01(\v2\x1d.eg.duckproxy.RollbackRequestH\x00R\brollback\x12;\n" +
	"\bdescribe\x18\x06 \x01(\v2\x1d.eg.duckproxy.DescribeRequestH\x00R\bdescribeB\x06\n" +
	"\x04body\"\x86\x03\n" +
	"\vServerFrame\x124\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.eg.duckproxy.ExecResponseH\x00R\x06result\x129\n" +
	"\acolumns\x18\x02 \x01(\v2\x1d.eg.duckproxy.ColumnsResponseH\x00R\acolumns\x12-\n" +
	"\x03row\x18\x03 \x01(\v2\x19.eg.duckproxy.RowResponseH\x00R\x03row\x120\n" +
	"\x04done\x18\x04 \x01(\v2\x1a.eg.duckproxy.DoneResponseH\x00R\x04done\x12*\n" +
	"\x02ok\x18\x05 \x01(\v2\x18.eg.duckproxy.OkResponseH\x00R\x02ok\x123\n" +
	"\x05error\x18\x06 \x01(\v2\x1b.eg.duckproxy.ErrorResponseH\x00R\x05error\x12<\n" +
	"\bdescribe\x18\a \x01(\v2\x1e.eg.duckproxy.DescribeResponseH\x00R\bdescribeB\x06\n" +
	"\x04bodyb\x06proto3"

var (
	file_eg_duckproxy_proto_rawDescOnce sync.Once
	file_eg_duckproxy_proto_rawDescData []byte
)

func file_eg_duckproxy_proto_rawDescGZIP() []byte {
	file_eg_duckproxy_proto_rawDescOnce.Do(func() {
		file_eg_duckproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eg_duckproxy_proto_rawDesc), len(file_eg_duckproxy_proto_rawDesc)))
	})
	return file_eg_duckproxy_proto_rawDescData
}

var file_eg_duckproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_eg_duckproxy_proto_goTypes = []any{
	(*Param)(nil),                 // 0: eg.duckproxy.Param
	(*Value)(nil),                 // 1: eg.duckproxy.Value
	(*Interval)(nil),              // 2: eg.duckproxy.Interval
	(*ListValue)(nil),             // 3: eg.duckproxy.ListValue
	(*StructValue)(nil),           // 4: eg.duckproxy.StructValue
	(*ExecRequest)(nil),           // 5: eg.duckproxy.ExecRequest
	(*QueryRequest)(nil),          // 6: eg.duckproxy.QueryRequest
	(*BeginRequest)(nil),          // 7: eg.duckproxy.BeginRequest
	(*CommitRequest)(nil),         // 8: eg.duckproxy.CommitRequest
	(*RollbackRequest)(nil),       // 9: eg.duckproxy.RollbackRequest
	(*DescribeRequest)(nil),       // 10: eg.duckproxy.DescribeRequest
	(*TypeMetadata)(nil),          // 11: eg.duckproxy.TypeMetadata
	(*DescribeResponse)(nil),      // 12: eg.duckproxy.DescribeResponse
	(*ExecResponse)(nil),          // 13: eg.duckproxy.ExecResponse
	(*ColumnsResponse)(nil),       // 14: eg.duckproxy.ColumnsResponse
	(*RowResponse)(nil),           // 15: eg.duckproxy.RowResponse
	(*DoneResponse)(nil),          // 16: eg.duckproxy.DoneResponse
	(*OkResponse)(nil),            // 17: eg.duckproxy.OkResponse
	(*ErrorResponse)(nil),         // 18: eg.duckproxy.ErrorResponse
	(*ClientFrame)(nil),           // 19: eg.duckproxy.ClientFrame
	(*ServerFrame)(nil),           // 20: eg.duckproxy.ServerFrame
	nil,                           // 21: eg.duckproxy.StructValue.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_eg_duckproxy_proto_depIdxs = []int32{
	1,  // 0: eg.duckproxy.Param.value:type_name -> eg.duckproxy.Value
	22, // 1: eg.duckproxy.Value.timestamp_value:type_name -> google.protobuf.Timestamp
	2,  // 2: eg.duckproxy.Value.interval_value:type_name -> eg.duckproxy.Interval
	3,  // 3: eg.duckproxy.Value.list_value:type_name -> eg.duckproxy.ListValue
	4,  // 4: eg.duckproxy.Value.struct_value:type_name -> eg.duckproxy.StructValue
	1,  // 5: eg.duckproxy.ListValue.values:type_name -> eg.duckproxy.Value
	21, // 6: eg.duckproxy.StructValue.fields:type_name -> eg.duckproxy.StructValue.FieldsEntry
	0,  // 7: eg.duckproxy.ExecRequest.args:type_name -> eg.duckproxy.Param
	0,  // 8: eg.duckproxy.QueryRequest.args:type_name -> eg.duckproxy.Param
	11, // 9: eg.duckproxy.DescribeResponse.params:type_name -> eg.duckproxy.TypeMetadata
	11, // 10: eg.duckproxy.DescribeResponse.columns:type_name -> eg.duckproxy.TypeMetadata
	1,  // 11: eg.duckproxy.RowResponse.values:type_name -> eg.duckproxy.Value
	5,  // 12: eg.duckproxy.ClientFrame.exec:type_name -> eg.duckproxy.ExecRequest
	6,  // 13: eg.duckproxy.ClientFrame.query:type_name -> eg.duckproxy.QueryRequest
	7,  // 14: eg.duckproxy.ClientFrame.begin:type_name -> eg.duckproxy.BeginRequest
	8,  // 15: eg.duckproxy.ClientFrame.commit:type_name -> eg.duckproxy.CommitRequest
	9,  // 16: eg.duckproxy.ClientFrame.rollback:type_name -> eg.duckproxy.RollbackRequest
	10, // 17: eg.duckproxy.ClientFrame.describe:type_name -> eg.duckproxy.DescribeRequest
	13, // 18: eg.duckproxy.ServerFrame.result:type_name -> eg.duckproxy.ExecResponse
	14, // 19: eg.duckproxy.ServerFrame.columns:type_name -> eg.duckproxy.ColumnsResponse
	15, // 20: eg.duckproxy.ServerFrame.row:type_name -> eg.duckproxy.RowResponse
	16, // 21: eg.duckproxy.ServerFrame.done:type_name -> eg.duckproxy.DoneResponse
	17, // 22: eg.duckproxy.ServerFrame.ok:type_name -> eg.duckproxy.OkResponse
	18, // 23: eg.duckproxy.ServerFrame.error:type_name -> eg.duckproxy.ErrorResponse
	12, // 24: eg.duckproxy.ServerFrame.describe:type_name -> eg.duckproxy.DescribeResponse
	1,  // 25: eg.duckproxy.StructValue.FieldsEntry.value:type_name -> eg.duckproxy.Value
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_eg_duckproxy_proto_init() }
func file_eg_duckproxy_proto_init() {
	if File_eg_duckproxy_proto != nil {
		return
	}
	file_eg_duckproxy_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_IsNull)(nil),
		(*Value_BoolValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_IntervalValue)(nil),
		(*Value_DecimalValue)(nil),
		(*Value_BignumValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_StructValue)(nil),
	}
	file_eg_duckproxy_proto_msgTypes[19].OneofWrappers = []any{
		(*ClientFrame_Exec)(nil),
		(*ClientFrame_Query)(nil),
		(*ClientFrame_Begin)(nil),
		(*ClientFrame_Commit)(nil),
		(*ClientFrame_Rollback)(nil),
		(*ClientFrame_Describe)(nil),
	}
	file_eg_duckproxy_proto_msgTypes[20].OneofWrappers = []any{
		(*ServerFrame_Result)(nil),
		(*ServerFrame_Columns)(nil),
		(*ServerFrame_Row)(nil),
		(*ServerFrame_Done)(nil),
		(*ServerFrame_Ok)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Describe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eg_duckproxy_proto_rawDesc), len(file_eg_duckproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_duckproxy_proto_goTypes,
		DependencyIndexes: file_eg_duckproxy_proto_depIdxs,
		MessageInfos:      file_eg_duckproxy_proto_msgTypes,
	}.Build()
	File_eg_duckproxy_proto = out.File
	file_eg_duckproxy_proto_goTypes = nil
	file_eg_duckproxy_proto_depIdxs = nil
}
