FROM ubuntu:oracular
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "cache buster 32cf44c8-3258-4dc8-ae5d-8487003baa41"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

# github cli initiated
# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
# RUN apt-add-repository https://cli.github.com/packages
# github cli completed

RUN echo "cache buster 32cf44c8-3258-4dc8-ae5d-8487003baa41"
RUN apt-get update
RUN apt-get -y install podman netavark rsync vim dput devscripts dh-make dput git uidmap dbus-user-session pinentry-tty tree python3 python3.12-venv
RUN apt-get -y install golang-1.23 eg duckdb

RUN ln -s /usr/lib/go-1.23/bin/go /usr/local/bin/go

RUN systemd-sysusers
RUN systemd-tmpfiles --create

RUN printf '%%wheel ALL=(ALL:ALL) NOPASSWD: ALL\n' | tee -a /etc/sudoers.d/egd

RUN systemctl enable eg-bindfs.service