// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: eg.actl.enqueued.proto

package runners

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enqueued struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt   string   `protobuf:"bytes,2,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt   string   `protobuf:"bytes,3,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Arch        string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Os          string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Cores       uint64   `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory      uint64   `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Vram        uint64   `protobuf:"varint,8,opt,name=vram,proto3" json:"vram,omitempty"`
	Ttl         uint64   `protobuf:"varint,9,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ClusterId   string   `protobuf:"bytes,10,opt,name=cluster_id,json=cid,proto3" json:"cluster_id,omitempty"`
	Entry       string   `protobuf:"bytes,11,opt,name=entry,json=entrypoint,proto3" json:"entry,omitempty"`
	InitiatedAt string   `protobuf:"bytes,12,opt,name=initiated_at,proto3" json:"initiated_at,omitempty"`
	CompletedAt string   `protobuf:"bytes,13,opt,name=completed_at,proto3" json:"completed_at,omitempty"`
	Description string   `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Vcsuri      string   `protobuf:"bytes,15,opt,name=vcsuri,proto3" json:"vcsuri,omitempty"`
	AllowShared bool     `protobuf:"varint,16,opt,name=allow_shared,proto3" json:"allow_shared,omitempty"`
	Labels      []string `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *Enqueued) Reset() {
	*x = Enqueued{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enqueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enqueued) ProtoMessage() {}

func (x *Enqueued) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enqueued.ProtoReflect.Descriptor instead.
func (*Enqueued) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{0}
}

func (x *Enqueued) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enqueued) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Enqueued) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Enqueued) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Enqueued) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Enqueued) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Enqueued) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Enqueued) GetVram() uint64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *Enqueued) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Enqueued) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Enqueued) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *Enqueued) GetInitiatedAt() string {
	if x != nil {
		return x.InitiatedAt
	}
	return ""
}

func (x *Enqueued) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Enqueued) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Enqueued) GetVcsuri() string {
	if x != nil {
		return x.Vcsuri
	}
	return ""
}

func (x *Enqueued) GetAllowShared() bool {
	if x != nil {
		return x.AllowShared
	}
	return false
}

func (x *Enqueued) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnqueuedSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query     string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset    uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit     uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Arch      string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Os        string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Cores     uint64   `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory    uint64   `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Vram      uint64   `protobuf:"varint,8,opt,name=vram,proto3" json:"vram,omitempty"`
	ClusterId string   `protobuf:"bytes,9,opt,name=cluster_id,json=cid,proto3" json:"cluster_id,omitempty"`
	Vcsuri    string   `protobuf:"bytes,10,opt,name=vcsuri,proto3" json:"vcsuri,omitempty"`
	Labels    []string `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *EnqueuedSearchRequest) Reset() {
	*x = EnqueuedSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedSearchRequest) ProtoMessage() {}

func (x *EnqueuedSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedSearchRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedSearchRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueuedSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetVram() uint64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetVcsuri() string {
	if x != nil {
		return x.Vcsuri
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnqueuedSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next  *EnqueuedSearchRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items []*Enqueued            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *EnqueuedSearchResponse) Reset() {
	*x = EnqueuedSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedSearchResponse) ProtoMessage() {}

func (x *EnqueuedSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedSearchResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedSearchResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueuedSearchResponse) GetNext() *EnqueuedSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *EnqueuedSearchResponse) GetItems() []*Enqueued {
	if x != nil {
		return x.Items
	}
	return nil
}

type EnqueuedCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedCreateRequest) Reset() {
	*x = EnqueuedCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCreateRequest) ProtoMessage() {}

func (x *EnqueuedCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCreateRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedCreateRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueuedCreateRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedCreateResponse) Reset() {
	*x = EnqueuedCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCreateResponse) ProtoMessage() {}

func (x *EnqueuedCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCreateResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedCreateResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueuedCreateResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedUpdateRequest) Reset() {
	*x = EnqueuedUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedUpdateRequest) ProtoMessage() {}

func (x *EnqueuedUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedUpdateRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedUpdateRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{5}
}

func (x *EnqueuedUpdateRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedUpdateResponse) Reset() {
	*x = EnqueuedUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedUpdateResponse) ProtoMessage() {}

func (x *EnqueuedUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedUpdateResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedUpdateResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{6}
}

func (x *EnqueuedUpdateResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedDequeueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedDequeueResponse) Reset() {
	*x = EnqueuedDequeueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedDequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedDequeueResponse) ProtoMessage() {}

func (x *EnqueuedDequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedDequeueResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedDequeueResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{7}
}

func (x *EnqueuedDequeueResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnqueuedDownloadRequest) Reset() {
	*x = EnqueuedDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedDownloadRequest) ProtoMessage() {}

func (x *EnqueuedDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedDownloadRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedDownloadRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{8}
}

type EnqueuedCompletedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnqueuedCompletedRequest) Reset() {
	*x = EnqueuedCompletedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCompletedRequest) ProtoMessage() {}

func (x *EnqueuedCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCompletedRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedCompletedRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{9}
}

type EnqueuedCompletedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedCompletedResponse) Reset() {
	*x = EnqueuedCompletedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCompletedResponse) ProtoMessage() {}

func (x *EnqueuedCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCompletedResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedCompletedResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{10}
}

func (x *EnqueuedCompletedResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedFindRequest) Reset() {
	*x = EnqueuedFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedFindRequest) ProtoMessage() {}

func (x *EnqueuedFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedFindRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedFindRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{11}
}

func (x *EnqueuedFindRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enqueued *Enqueued `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
}

func (x *EnqueuedFindResponse) Reset() {
	*x = EnqueuedFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eg_actl_enqueued_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueuedFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedFindResponse) ProtoMessage() {}

func (x *EnqueuedFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedFindResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedFindResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{12}
}

func (x *EnqueuedFindResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

var File_eg_actl_enqueued_proto protoreflect.FileDescriptor

var file_eg_actl_enqueued_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74,
	0x6c, 0x22, 0xcc, 0x03, 0x0a, 0x08, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x76, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x17, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x63, 0x73, 0x75, 0x72, 0x69, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x63, 0x73, 0x75, 0x72, 0x69, 0x12, 0x22, 0x0a, 0x0c,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x12, 0x17, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4a, 0x05, 0x08, 0x11, 0x10, 0xe8, 0x07,
	0x22, 0x92, 0x02, 0x0a, 0x15, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x76, 0x72, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x63, 0x73, 0x75, 0x72, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x63, 0x73, 0x75, 0x72, 0x69, 0x12, 0x17, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18,
	0xe8, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4a, 0x05,
	0x08, 0x0b, 0x10, 0xe8, 0x07, 0x22, 0x75, 0x0a, 0x16, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x45, 0x0a, 0x15,
	0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74,
	0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x16, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x15, 0x45,
	0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c,
	0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x22, 0x46, 0x0a, 0x16, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08,
	0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x48, 0x0a, 0x17, 0x45, 0x6e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74,
	0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x08, 0x65, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1a, 0x0a, 0x18, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x19, 0x45,
	0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e,
	0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x07, 0x65,
	0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x45,
	0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x67, 0x2e, 0x61, 0x63, 0x74, 0x6c, 0x2e,
	0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eg_actl_enqueued_proto_rawDescOnce sync.Once
	file_eg_actl_enqueued_proto_rawDescData = file_eg_actl_enqueued_proto_rawDesc
)

func file_eg_actl_enqueued_proto_rawDescGZIP() []byte {
	file_eg_actl_enqueued_proto_rawDescOnce.Do(func() {
		file_eg_actl_enqueued_proto_rawDescData = protoimpl.X.CompressGZIP(file_eg_actl_enqueued_proto_rawDescData)
	})
	return file_eg_actl_enqueued_proto_rawDescData
}

var file_eg_actl_enqueued_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_eg_actl_enqueued_proto_goTypes = []interface{}{
	(*Enqueued)(nil),                  // 0: eg.actl.Enqueued
	(*EnqueuedSearchRequest)(nil),     // 1: eg.actl.EnqueuedSearchRequest
	(*EnqueuedSearchResponse)(nil),    // 2: eg.actl.EnqueuedSearchResponse
	(*EnqueuedCreateRequest)(nil),     // 3: eg.actl.EnqueuedCreateRequest
	(*EnqueuedCreateResponse)(nil),    // 4: eg.actl.EnqueuedCreateResponse
	(*EnqueuedUpdateRequest)(nil),     // 5: eg.actl.EnqueuedUpdateRequest
	(*EnqueuedUpdateResponse)(nil),    // 6: eg.actl.EnqueuedUpdateResponse
	(*EnqueuedDequeueResponse)(nil),   // 7: eg.actl.EnqueuedDequeueResponse
	(*EnqueuedDownloadRequest)(nil),   // 8: eg.actl.EnqueuedDownloadRequest
	(*EnqueuedCompletedRequest)(nil),  // 9: eg.actl.EnqueuedCompletedRequest
	(*EnqueuedCompletedResponse)(nil), // 10: eg.actl.EnqueuedCompletedResponse
	(*EnqueuedFindRequest)(nil),       // 11: eg.actl.EnqueuedFindRequest
	(*EnqueuedFindResponse)(nil),      // 12: eg.actl.EnqueuedFindResponse
}
var file_eg_actl_enqueued_proto_depIdxs = []int32{
	1,  // 0: eg.actl.EnqueuedSearchResponse.next:type_name -> eg.actl.EnqueuedSearchRequest
	0,  // 1: eg.actl.EnqueuedSearchResponse.items:type_name -> eg.actl.Enqueued
	0,  // 2: eg.actl.EnqueuedCreateRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 3: eg.actl.EnqueuedCreateResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 4: eg.actl.EnqueuedUpdateRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 5: eg.actl.EnqueuedUpdateResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 6: eg.actl.EnqueuedDequeueResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 7: eg.actl.EnqueuedCompletedResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 8: eg.actl.EnqueuedFindRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 9: eg.actl.EnqueuedFindResponse.enqueued:type_name -> eg.actl.Enqueued
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_eg_actl_enqueued_proto_init() }
func file_eg_actl_enqueued_proto_init() {
	if File_eg_actl_enqueued_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eg_actl_enqueued_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enqueued); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedDequeueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedCompletedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedCompletedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eg_actl_enqueued_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueuedFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eg_actl_enqueued_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_actl_enqueued_proto_goTypes,
		DependencyIndexes: file_eg_actl_enqueued_proto_depIdxs,
		MessageInfos:      file_eg_actl_enqueued_proto_msgTypes,
	}.Build()
	File_eg_actl_enqueued_proto = out.File
	file_eg_actl_enqueued_proto_rawDesc = nil
	file_eg_actl_enqueued_proto_goTypes = nil
	file_eg_actl_enqueued_proto_depIdxs = nil
}
