// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: eg.actl.enqueued.proto

package runners

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enqueued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Cores         uint64                 `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory        uint64                 `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Vram          uint64                 `protobuf:"varint,8,opt,name=vram,proto3" json:"vram,omitempty"`
	Ttl           uint64                 `protobuf:"varint,9,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ClusterId     string                 `protobuf:"bytes,10,opt,name=cluster_id,json=cid,proto3" json:"cluster_id,omitempty"`
	Entry         string                 `protobuf:"bytes,11,opt,name=entry,json=entrypoint,proto3" json:"entry,omitempty"`
	InitiatedAt   string                 `protobuf:"bytes,12,opt,name=initiated_at,proto3" json:"initiated_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,13,opt,name=completed_at,proto3" json:"completed_at,omitempty"`
	Description   string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	VcsUri        string                 `protobuf:"bytes,15,opt,name=vcs_uri,proto3" json:"vcs_uri,omitempty"`
	AllowShared   bool                   `protobuf:"varint,16,opt,name=allow_shared,proto3" json:"allow_shared,omitempty"`
	AccountId     string                 `protobuf:"bytes,17,opt,name=account_id,proto3" json:"account_id,omitempty"`
	Mimetype      string                 `protobuf:"bytes,18,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,19,opt,name=uploaded_by,proto3" json:"uploaded_by,omitempty"`
	Labels        []string               `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enqueued) Reset() {
	*x = Enqueued{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enqueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enqueued) ProtoMessage() {}

func (x *Enqueued) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enqueued.ProtoReflect.Descriptor instead.
func (*Enqueued) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{0}
}

func (x *Enqueued) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enqueued) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Enqueued) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Enqueued) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Enqueued) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Enqueued) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Enqueued) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Enqueued) GetVram() uint64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *Enqueued) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Enqueued) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Enqueued) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *Enqueued) GetInitiatedAt() string {
	if x != nil {
		return x.InitiatedAt
	}
	return ""
}

func (x *Enqueued) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Enqueued) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Enqueued) GetVcsUri() string {
	if x != nil {
		return x.VcsUri
	}
	return ""
}

func (x *Enqueued) GetAllowShared() bool {
	if x != nil {
		return x.AllowShared
	}
	return false
}

func (x *Enqueued) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Enqueued) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Enqueued) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *Enqueued) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnqueuedSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Cores         uint64                 `protobuf:"varint,6,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory        uint64                 `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Vram          uint64                 `protobuf:"varint,8,opt,name=vram,proto3" json:"vram,omitempty"`
	ClusterId     string                 `protobuf:"bytes,9,opt,name=cluster_id,json=cid,proto3" json:"cluster_id,omitempty"`
	VcsUri        string                 `protobuf:"bytes,10,opt,name=vcs_uri,proto3" json:"vcs_uri,omitempty"`
	Labels        []string               `protobuf:"bytes,1000,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedSearchRequest) Reset() {
	*x = EnqueuedSearchRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedSearchRequest) ProtoMessage() {}

func (x *EnqueuedSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedSearchRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedSearchRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueuedSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetCores() uint64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetVram() uint64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *EnqueuedSearchRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetVcsUri() string {
	if x != nil {
		return x.VcsUri
	}
	return ""
}

func (x *EnqueuedSearchRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnqueuedSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *EnqueuedSearchRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Enqueued            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedSearchResponse) Reset() {
	*x = EnqueuedSearchResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedSearchResponse) ProtoMessage() {}

func (x *EnqueuedSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedSearchResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedSearchResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueuedSearchResponse) GetNext() *EnqueuedSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *EnqueuedSearchResponse) GetItems() []*Enqueued {
	if x != nil {
		return x.Items
	}
	return nil
}

type EnqueuedCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedCreateRequest) Reset() {
	*x = EnqueuedCreateRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCreateRequest) ProtoMessage() {}

func (x *EnqueuedCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCreateRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedCreateRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueuedCreateRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedCreateResponse) Reset() {
	*x = EnqueuedCreateResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCreateResponse) ProtoMessage() {}

func (x *EnqueuedCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCreateResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedCreateResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueuedCreateResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedUpdateRequest) Reset() {
	*x = EnqueuedUpdateRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedUpdateRequest) ProtoMessage() {}

func (x *EnqueuedUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedUpdateRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedUpdateRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{5}
}

func (x *EnqueuedUpdateRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedUpdateResponse) Reset() {
	*x = EnqueuedUpdateResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedUpdateResponse) ProtoMessage() {}

func (x *EnqueuedUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedUpdateResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedUpdateResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{6}
}

func (x *EnqueuedUpdateResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedDequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedDequeueResponse) Reset() {
	*x = EnqueuedDequeueResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedDequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedDequeueResponse) ProtoMessage() {}

func (x *EnqueuedDequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedDequeueResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedDequeueResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{7}
}

func (x *EnqueuedDequeueResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

func (x *EnqueuedDequeueResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type EnqueuedDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedDownloadRequest) Reset() {
	*x = EnqueuedDownloadRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedDownloadRequest) ProtoMessage() {}

func (x *EnqueuedDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedDownloadRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedDownloadRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{8}
}

type EnqueuedCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedCompletedRequest) Reset() {
	*x = EnqueuedCompletedRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCompletedRequest) ProtoMessage() {}

func (x *EnqueuedCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCompletedRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedCompletedRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{9}
}

type EnqueuedCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedCompletedResponse) Reset() {
	*x = EnqueuedCompletedResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedCompletedResponse) ProtoMessage() {}

func (x *EnqueuedCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedCompletedResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedCompletedResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{10}
}

func (x *EnqueuedCompletedResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedFindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedFindRequest) Reset() {
	*x = EnqueuedFindRequest{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedFindRequest) ProtoMessage() {}

func (x *EnqueuedFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedFindRequest.ProtoReflect.Descriptor instead.
func (*EnqueuedFindRequest) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{11}
}

func (x *EnqueuedFindRequest) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

type EnqueuedFindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      *Enqueued              `protobuf:"bytes,1,opt,name=enqueued,json=enqueue,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuedFindResponse) Reset() {
	*x = EnqueuedFindResponse{}
	mi := &file_eg_actl_enqueued_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuedFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuedFindResponse) ProtoMessage() {}

func (x *EnqueuedFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eg_actl_enqueued_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuedFindResponse.ProtoReflect.Descriptor instead.
func (*EnqueuedFindResponse) Descriptor() ([]byte, []int) {
	return file_eg_actl_enqueued_proto_rawDescGZIP(), []int{12}
}

func (x *EnqueuedFindResponse) GetEnqueued() *Enqueued {
	if x != nil {
		return x.Enqueued
	}
	return nil
}

var File_eg_actl_enqueued_proto protoreflect.FileDescriptor

const file_eg_actl_enqueued_proto_rawDesc = "" +
	"\n" +
	"\x16eg.actl.enqueued.proto\x12\aeg.actl\"\xac\x04\n" +
	"\bEnqueued\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\n" +
	"updated_at\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x14\n" +
	"\x05cores\x18\x06 \x01(\x04R\x05cores\x12\x16\n" +
	"\x06memory\x18\a \x01(\x04R\x06memory\x12\x12\n" +
	"\x04vram\x18\b \x01(\x04R\x04vram\x12\x10\n" +
	"\x03ttl\x18\t \x01(\x04R\x03ttl\x12\x17\n" +
	"\n" +
	"cluster_id\x18\n" +
	" \x01(\tR\x03cid\x12\x19\n" +
	"\x05entry\x18\v \x01(\tR\n" +
	"entrypoint\x12\"\n" +
	"\finitiated_at\x18\f \x01(\tR\finitiated_at\x12\"\n" +
	"\fcompleted_at\x18\r \x01(\tR\fcompleted_at\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x18\n" +
	"\avcs_uri\x18\x0f \x01(\tR\avcs_uri\x12\"\n" +
	"\fallow_shared\x18\x10 \x01(\bR\fallow_shared\x12\x1e\n" +
	"\n" +
	"account_id\x18\x11 \x01(\tR\n" +
	"account_id\x12\x1a\n" +
	"\bmimetype\x18\x12 \x01(\tR\bmimetype\x12 \n" +
	"\vuploaded_by\x18\x13 \x01(\tR\vuploaded_by\x12\x17\n" +
	"\x06labels\x18\xe8\a \x03(\tR\x06labelsJ\x05\b\x14\x10\xe8\a\"\x94\x02\n" +
	"\x15EnqueuedSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x14\n" +
	"\x05cores\x18\x06 \x01(\x04R\x05cores\x12\x16\n" +
	"\x06memory\x18\a \x01(\x04R\x06memory\x12\x12\n" +
	"\x04vram\x18\b \x01(\x04R\x04vram\x12\x17\n" +
	"\n" +
	"cluster_id\x18\t \x01(\tR\x03cid\x12\x18\n" +
	"\avcs_uri\x18\n" +
	" \x01(\tR\avcs_uri\x12\x17\n" +
	"\x06labels\x18\xe8\a \x03(\tR\x06labelsJ\x05\b\v\x10\xe8\a\"u\n" +
	"\x16EnqueuedSearchResponse\x122\n" +
	"\x04next\x18\x01 \x01(\v2\x1e.eg.actl.EnqueuedSearchRequestR\x04next\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.eg.actl.EnqueuedR\x05items\"E\n" +
	"\x15EnqueuedCreateRequest\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"F\n" +
	"\x16EnqueuedCreateResponse\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"E\n" +
	"\x15EnqueuedUpdateRequest\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"F\n" +
	"\x16EnqueuedUpdateResponse\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"l\n" +
	"\x17EnqueuedDequeueResponse\x12-\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\benqueued\x12\"\n" +
	"\faccess_token\x18\x02 \x01(\tR\faccess_token\"\x19\n" +
	"\x17EnqueuedDownloadRequest\"\x1a\n" +
	"\x18EnqueuedCompletedRequest\"I\n" +
	"\x19EnqueuedCompletedResponse\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"C\n" +
	"\x13EnqueuedFindRequest\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueue\"D\n" +
	"\x14EnqueuedFindResponse\x12,\n" +
	"\benqueued\x18\x01 \x01(\v2\x11.eg.actl.EnqueuedR\aenqueueb\x06proto3"

var (
	file_eg_actl_enqueued_proto_rawDescOnce sync.Once
	file_eg_actl_enqueued_proto_rawDescData []byte
)

func file_eg_actl_enqueued_proto_rawDescGZIP() []byte {
	file_eg_actl_enqueued_proto_rawDescOnce.Do(func() {
		file_eg_actl_enqueued_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eg_actl_enqueued_proto_rawDesc), len(file_eg_actl_enqueued_proto_rawDesc)))
	})
	return file_eg_actl_enqueued_proto_rawDescData
}

var file_eg_actl_enqueued_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_eg_actl_enqueued_proto_goTypes = []any{
	(*Enqueued)(nil),                  // 0: eg.actl.Enqueued
	(*EnqueuedSearchRequest)(nil),     // 1: eg.actl.EnqueuedSearchRequest
	(*EnqueuedSearchResponse)(nil),    // 2: eg.actl.EnqueuedSearchResponse
	(*EnqueuedCreateRequest)(nil),     // 3: eg.actl.EnqueuedCreateRequest
	(*EnqueuedCreateResponse)(nil),    // 4: eg.actl.EnqueuedCreateResponse
	(*EnqueuedUpdateRequest)(nil),     // 5: eg.actl.EnqueuedUpdateRequest
	(*EnqueuedUpdateResponse)(nil),    // 6: eg.actl.EnqueuedUpdateResponse
	(*EnqueuedDequeueResponse)(nil),   // 7: eg.actl.EnqueuedDequeueResponse
	(*EnqueuedDownloadRequest)(nil),   // 8: eg.actl.EnqueuedDownloadRequest
	(*EnqueuedCompletedRequest)(nil),  // 9: eg.actl.EnqueuedCompletedRequest
	(*EnqueuedCompletedResponse)(nil), // 10: eg.actl.EnqueuedCompletedResponse
	(*EnqueuedFindRequest)(nil),       // 11: eg.actl.EnqueuedFindRequest
	(*EnqueuedFindResponse)(nil),      // 12: eg.actl.EnqueuedFindResponse
}
var file_eg_actl_enqueued_proto_depIdxs = []int32{
	1,  // 0: eg.actl.EnqueuedSearchResponse.next:type_name -> eg.actl.EnqueuedSearchRequest
	0,  // 1: eg.actl.EnqueuedSearchResponse.items:type_name -> eg.actl.Enqueued
	0,  // 2: eg.actl.EnqueuedCreateRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 3: eg.actl.EnqueuedCreateResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 4: eg.actl.EnqueuedUpdateRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 5: eg.actl.EnqueuedUpdateResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 6: eg.actl.EnqueuedDequeueResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 7: eg.actl.EnqueuedCompletedResponse.enqueued:type_name -> eg.actl.Enqueued
	0,  // 8: eg.actl.EnqueuedFindRequest.enqueued:type_name -> eg.actl.Enqueued
	0,  // 9: eg.actl.EnqueuedFindResponse.enqueued:type_name -> eg.actl.Enqueued
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_eg_actl_enqueued_proto_init() }
func file_eg_actl_enqueued_proto_init() {
	if File_eg_actl_enqueued_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eg_actl_enqueued_proto_rawDesc), len(file_eg_actl_enqueued_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eg_actl_enqueued_proto_goTypes,
		DependencyIndexes: file_eg_actl_enqueued_proto_depIdxs,
		MessageInfos:      file_eg_actl_enqueued_proto_msgTypes,
	}.Build()
	File_eg_actl_enqueued_proto = out.File
	file_eg_actl_enqueued_proto_goTypes = nil
	file_eg_actl_enqueued_proto_depIdxs = nil
}
