name: macosx release
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  macos:
    name: release
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Setup Go environment on macOS
      id: setup-go-macos
      uses: actions/setup-go@v5 # Using setup-go action for Go installation and caching
      with:
        go-version: 'stable' # Use 'stable' to always get the latest stable Go version
        cache: true # Enable caching for Go modules and build cache
        check-latest: true # Ensures the latest stable version is always used
    - name: Cache Go module and build cache
      id: cache-go-install-deps # Add an ID for this cache step
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.setup-go-macos.outputs.go-mod-cache }} # Path to Go module cache
          ${{ steps.setup-go-macos.outputs.go-build-cache }} # Path to Go build cache
        key: ${{ runner.os }}-go-${{ steps.setup-go-macos.outputs.go-version }}-installed # Unique key for this cache
        restore-keys: |
          ${{ runner.os }}-go-${{ steps.setup-go-macos.outputs.go-version }}-installed- # Fallback keys
    - uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: 'duckdb gpgme tree'
        verbose: false

    - name: Checkout repository
      uses: actions/checkout@v4
    - name: build
      run: |
        CGO_ENABLED=1 CGO_LDFLAGS="-L/opt/homebrew/lib" go build -buildmode=c-shared --tags duckdb_use_lib ./...
        ~/go/bin/eg compute baremetal -vv release/eg/darwin